controller_frequency: 5.0
recovery_behaviour_enabled: true

recovery_behaviors:
  - {name: BackupRecovery, type: "backup_recovery::BackupRecovery"}

# trigger recovery behaviors if the robot doesn't cover a certain distance (oscillation_distance)
# in a certain amount of time (oscillation_timeout)
oscillation_distance: 0.5
oscillation_timeout: 3.5

BackupRecovery:
  backwards_vel: -0.4
  backup_dist: 0.5
  frequency: 20.0

GlobalPlanner:
  old_navfn_behavior: true  # https://answers.ros.org/question/350510/some-errors-when-using-globalplanner/
  allow_unknown: true       # Specifies whether or not to allow navfn to create plans that traverse unknown space.
  default_tolerance: 0.5    # A tolerance on the goal point for the planner.
  cost_factor: 0.55
  neutral_cost: 66
  lethal_cost: 253
  outline_map: true

DWAPlannerROS:
  # forward simulation
  sim_time: 4.0
  vx_samples: 20
  vy_samples: 1     # this should be 0 (UGV is non-holonomic), but the min. value this param can be is 1
  vth_samples: 40

  # trajectory scoring
  path_distance_bias: 32.0
  goal_distance_bias: 20.0
  occdist_scale: 0.02

  # Robot configuration parameters
  acc_lim_x: 5.0
  acc_lim_y: 0
  acc_lim_th: 3.2
  acc_lim_trans: 5.0

  max_vel_x: 2.0
  min_vel_x: 0.0
  max_vel_y: 0
  min_vel_y: 0

  max_vel_trans: 2.0
  min_vel_trans: 0.1
  max_vel_theta: 2.0
  min_vel_theta: 0.2

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 3.14
  xy_goal_tolerance: 0.6
  latch_xy_goal_tolerance: false
